# Generated by Django 5.2.4 on 2025-08-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_link_alter_course_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
        migrations.AlterField(
            model_name='course',
            name='stars',
            field=models.IntegerField(default=4),
        ),
    ]
