# Generated by Django 5.2.4 on 2025-08-03 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_slug_alter_course_description_purchasedcourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
        migrations.DeleteModel(
            name='PurchasedCourse',
        ),
    ]
