# Generated by Django 5.2.4 on 2025-08-03 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_purchasedcourse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchasedCourse',
        ),
    ]
