# Generated by Django 5.2.4 on 2025-08-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_purchasedcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='ELearningSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='elearning_images/')),
                ('background_color', models.CharField(default='#fafafa', max_length=20)),
                ('points', models.TextField(help_text='Use newline to separate each point (e.g., item1\\nitem2)')),
            ],
        ),
    ]
