# Generated by Django 5.2.4 on 2025-08-04 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_elearningsection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ELearningSection',
        ),
    ]
