# Generated by Django 5.2.4 on 2025-08-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_delete_elearningsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ELearningSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('bullet1', models.CharField(max_length=255)),
                ('bullet2', models.CharField(max_length=255)),
                ('bullet3', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='section_images/')),
            ],
        ),
    ]
