# Generated by Django 5.2.4 on 2025-08-05 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_course_is_trending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_trending',
        ),
    ]
